# Initialize new container using official Ubuntu base image
FROM ubuntu

# Set home directory & copy project source code
ENV HOME="/home"
ENV PROJECT="$HOME/repos/{{project_name}}"
WORKDIR $PROJECT
COPY . $PROJECT

# Install OS packages
RUN apt-get update
RUN xargs -a packages.txt apt-get install -y

# Install Python packages
ENV PYTHON_VERSION=3.11.9
ENV PYENV_VERSION=3.11.9
ENV PYENV_ROOT="$HOME/.pyenv"
ENV PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"
RUN set -ex \
    && curl https://pyenv.run | bash \
    && pyenv update \
    && pyenv install $PYTHON_VERSION \
    && pyenv global $PYTHON_VERSION \
    && pyenv rehash
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# Run tail command so container stays alive
CMD ["tail", "-f", "/dev/null"]
